[build]
    command = "npm run scss"

[[redirects]]
  from = "https://intvhq.com/*"
  to = "https://interversehq.com/:splat"
  status = 301
  force = true

  [[redirects]]
  from = "https://www.intvhq.com/*"
  to = "https://www.interversehq.com/:splat"
  status = 301
  force = true